### ISSUE TITLE
Adding texture images

### ISSUE THREAD

**Issue by mitchwallerstedt** [DanElbert/dungeon#52]
Is there a way to manually add texture images for the background grid? I've got a couple water background images as examples I'd like to be able to pull in as textures. 
![Water Texture 1 (8 5x11)](https://user-images.githubusercontent.com/63200173/78503197-c2dfcc80-772a-11ea-93d1-a26e4dee7cf0.jpg)
![Water Texture 2 (8 5x11)](https://user-images.githubusercontent.com/63200173/78503201-c5dabd00-772a-11ea-9dd3-8574e3f6994f.jpg)

**Comment by DanElbert** [comment]
Added the ability to upload custom background images per-campaign.
