### ISSUE TITLE
Issue adding token while in map

### ISSUE THREAD

**Issue by marcusmaday** [DanElbert/dungeon#61]
When I'm adding a token from within a map, it doesn't show the token for me be to add in the selection box after i have created it.  Once i leave the map and come back, it is available.

**Comment by DanElbert** [comment]
Vue reactivity bug.

Should be fixed now.

8593a2306407ddb1b7bc4282800f638394e014ef

**Comment by marcusmaday** [comment]
Awesome, thanks @DanElbert!
